.travis.yml, Makefile, requirements.txt
Added Travis-CI configuration and mypy checks
=> Added Travis-CI config

.travis.yml
=> [DPTOOLS-1804] Register to Pypi

metadata_service/api/user.py, metadata_service/entity/user_detail.py, metadata_service/proxy/neo4j_proxy.py, tests/unit/test_neo4j_proxy.py
Add the manager full name as user endpoint payload.
Note: We need to verify whether we have the data correctly in manager.
=> Add manager info in user endpoint payload

metadata_service/proxy/atlas_proxy.py, requirements.txt, setup.py, tests/unit/proxy/test_atlas_proxy.py
This PR implements the column feature for the table detail page on Amundsen. 
Also updates the atlasclient version and introduced the new version for Amundsen metadata library itself.
=> Implement the column information for atlas proxy

.github/PULL_REQUEST_TEMPLATE.md
Mostly copied from Apache Airflow
=> Adds the PR template for Amundsen Metadata Library

README.md
Make sure you have checked **all** steps below.
- Example: "Updates the version of Flask to v1.0.2"
This PR adds the basic information needed to know about the repository on the readme file. 
1. Subject is separated from body by a blank line
1. Subject is limited to 50 characters (not including Jira issue reference)
1. Subject does not end with a period
1. Subject uses the imperative mood ("add", not "adding")
1. Body wraps at 72 characters
1. Body explains "what" and "why", not "how"
=> Adds the build status and version information to Readme.md

.travis.yml, Makefile
Publish Docker image in CI
Performed `make build-push-image`
N/A
=> [DPTOOLS-2252] Publish Docker image in CI

metadata_service/proxy/neo4j_proxy.py, setup.py
User node should be create only, otherwise it will override existing node, causing all other attributes of the user showing empty
=> Remove Merge on Match on User Model in add_table_relation_by_user method

docs/proxy/atlas/column_configs.md, docs/proxy/atlas_proxy.md, metadata_service/proxy/atlas_proxy.py, tests/unit/proxy/test_atlas_proxy.py
This PR implements the column statistics available for the atlas proxy, that was not there before. 
This updates the test cases related to get table details from atlas proxy. 
Documentation explains how to add the column statistics attributes in the atlas itself, including the code to do that using Python. 
=> Implements the column statistics for atlas proxy

metadata_service/proxy/neo4j_proxy.py, setup.py
MERGE (u:User {key: $user_email})
on CREATE SET u.email: $user_email, u.key: $user_email
is not working. We need to change it to
MERGE (u:User {key: $user_email})
on CREATE SET u={email: $user_email, key: $user_email}
=> fix user query

docs/proxy/atlas/metadata_configs.md, docs/proxy/atlas_proxy.md, metadata_service/api/popular_tables.py, metadata_service/config.py, metadata_service/proxy/atlas_proxy.py, metadata_service/proxy/base_proxy.py, metadata_service/proxy/neo4j_proxy.py, requirements.txt, setup.py, tests/unit/proxy/fixtures/atlas_test_data.py, tests/unit/proxy/test_atlas_proxy.py
This implements the popular table support for the Atlas Proxy within Amundsen. Adds the documentation to generate required relationships between User Access, Metadata and Tables. It also explains how to generate the popularity score of a data source, along with sample scripts that can be used to generate that in Atlas. 
Moved a lot of helper functions in Python atlasclient directly, and wrote the test cases there. and also updated test cases based on the new implementations of Popular Tables. 
To support Popular Tables API, and to generate required relationships in Atlas. 
- In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License …
=> Updates to popular tables API for Atlas proxy

metadata_service/entity/popular_table.py, metadata_service/entity/table_detail.py, metadata_service/entity/tag_detail.py, metadata_service/entity/user_detail.py, requirements.txt, setup.py
Use attrs to generate python classes and marshmallow-annotations to generate schemas.
This makes it far, far less painful to add new entities.
None modified. Refactor.
None modified. Refactor.
- [ x ] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
- [ x ] PR includes a summary of changes. 
- [ x ] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [ x ] In case of new functionality, my PR adds documentation that describes how to …
=> Use attrs + marshmallow-annotations for entities

metadata_service/entity/table_detail.py
With https://github.com/lyft/amundsenmetadatalibrary/pull/64/files, we have checked in some models that currently are not used. Going to remove those unless we plan to use those in the near future.
=> Remove unused models

metadata_service/proxy/neo4j_proxy.py, setup.py
Remove `_OF`-type secondary relationships as they seem to have little benefit. See https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1563487877254000 and https://gist.github.com/friendtocephalopods/14c5b59f3ace8772ca2d502c928bb641 for a more detailed analysis of why this is okay.
No tests modified, since it's a refactor that shouldn't change test behavior.
No documentation added or modified.
- [x ] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
- [x ] PR includes a summary of changes. 
- [x …
=> Change neo4j relationships to single-directional

metadata_service/proxy/atlas_proxy.py, setup.py, tests/unit/proxy/test_atlas_proxy.py
This PR makes sure to use the indexed search, to improve the response time. This also makes sure that popular tables are fetched based on the popularityScore. 
=> Uses basic search instead of advanced DSL for popular tables

README.md, public.Dockerfile, setup.py
Optimize docker - see https://github.com/lyft/amundsen/issues/109
Manually tested locally with `docker build ...`
Should be on par with the Search service now
=> optimize docker

metadata_service/api/column.py, metadata_service/api/table.py, setup.py, tests/unit/api/test_redshit_disable_comment_edit.py
The data field in requests is widely used while json is not. Internally Lyft's request client doesn't respect json field...
=> Change the field to data

metadata_service/api/popular_tables.py, setup.cfg, tests/unit/api/test_column_description_api.py, tests/unit/api/test_popular_tables_api.py
* Adds unit tests for the column description and the popular tables APIs.
* Excludes import statements from the test coverage report. This will change the code coverage on all files, but it will now be more reflective of code actually tested. 
This mostly adds unit tests. 
None
=> Adds unit tests

metadata_service/api/table.py, tests/unit/api/table/table_test_case.py, tests/unit/api/table/test_table_description_api.py, tests/unit/api/table/test_table_detail_api.py, tests/unit/api/table/test_table_owner_api.py, tests/unit/api/table/test_table_tag_api.py, tests/unit/api/test_column_description_api.py, tests/unit/api/test_popular_tables_api.py
* Adds unit tests for the table APIs
* Removes '/table/<path:table_uri>/tag' API path as it does not work. 
* Removes unused code in the table API.
* Uses `BasicTestCase` as the best for other unit tests. 
This mostly adds unit tests. 
None 
=> Unit tests for table

public.Dockerfile
Similar to https://github.com/lyft/amundsensearchlibrary/pull/66
=> Pin Docker to Python 3.7

metadata_service/proxy/atlas_proxy.py, tests/unit/proxy/fixtures/atlas_test_data.py, tests/unit/proxy/test_atlas_proxy.py
Feature for integrating user follow api with atlas proxy to enable bookmarks.
Following functions are implemented for the bookmarks feature in `atlas_proxy.py`
`add_table_relation_by_user`
`delete_table_relation_by_user`
`get_table_by_user_relation`
`test_atlas_proxy.py` was added with respective tests
=> Bookmarks implementation for Atlas proxy

metadata_service/__init__.py, metadata_service/api/table.py, metadata_service/config.py, metadata_service/entity/table_detail.py, metadata_service/exception.py, metadata_service/proxy/atlas_proxy.py, metadata_service/proxy/base_proxy.py, metadata_service/proxy/neo4j_proxy.py, setup.py, tests/unit/api/table/test_table_detail_api.py, tests/unit/api/table/test_table_tag_api.py, tests/unit/proxy/test_atlas_proxy.py, tests/unit/proxy/test_neo4j_proxy.py
Add badge support. Badge is non UI modifiable tag which allows other service to ingest.
Test with the following:
```tfeng@tfeng-mbp143 ~/src/amundsenmetadata-private (master) $ curl -X GET http://0.0.0.0:5000/table/"hive://gold.schema/table"/tag/?tag_type=badge
[{"tag_type": "badge", "tag_name": "test-tag1"}]
tfeng@tfeng-mbp143 ~/src/amundsenmetadata-private (master) $ curl -X PUT http://0.0.0.0:5000/table/"hive://gold.schema/table"/tag/test-tag2?tag_type=badge
{"message": "The tag test-tag2 for table_uri hive://gold.schema/table with type badge is not added successfully as badge is not part of the whitelist"}
tfeng@tfeng-mbp143 ~/src/amundsenmetadata-private (master) $ curl -X PUT http://0.0.0.0:5000/table/"hive://gold.schema/table"/tag/test-tag?tag_type=badge
{"message": "The tag …
```
=> Add badge tag type support

metadata_service/__init__.py, metadata_service/config.py, setup.py
In order to have the proper monitoring in place, based on the internal requirements it would be much easier to have a configurable configuration file for logging. 
Following is the example:
```
[loggers]
keys=root,amundsenmetadata,werkzeug
[handlers]
keys=consoleHandler
[formatters]
keys=amundsenFormatter
[logger_root]
level=DEBUG
handlers=consoleHandler
[logger_werkzeug]
level=DEBUG
handlers=consoleHandler
qualname=werkzeug
propagate=0
[logger_amundsenmetadata]
level=DEBUG
handlers=consoleHandler
qualname=amundsenmetadata
propagate=0
[handler_consoleHandler]
class=StreamHandler
level=DEBUG
formatter=amundsenFormatter
args=(sys.stdout,)
[formatter_amundsenFormatter]
format=%(asctime)s.%(msecs)03d [%(levelname)s][%(name)s] %(module)s.%(funcName)s:%(lineno)d (%(process)d:%(threadName)s) - …
```
=> Implements the functionality to customize the logging based on config file

Makefile, metadata_service/oidc_config.py, public.Dockerfile, setup.py
This adds a second docker container that has all the oidc configuration you need and instructions on how to use it. I will add a new helmchart next that uses this new image. 
This change only includes integration code and build configs.
=> Adding oidc image to the metadata service

metadata_service/proxy/neo4j_proxy.py, setup.py
Fixed a Cypher query that was not sorting frequently used table
Integration tested.
N/A
=> Fix Cypher query on frequently used table on user

metadata_service/__init__.py, metadata_service/config.py, setup.py
Forgot to enable all the existing logger for the fileConfig. 
NA
NA
=> Implements the functionality to customize the logging based on config file 

metadata_service/proxy/atlas_proxy.py, metadata_service/proxy/neo4j_proxy.py, requirements.txt
This will fix the columns order in the frontend. Fixes the metadata API to always return the sorted columns. 
N/A
N/A
=> Respects the column order, and pass it in ordered list to frontend

.gitignore, metadata_service/__init__.py, metadata_service/api/dashboard.py, metadata_service/api/swagger_doc/dashboard/detail_get.yml, metadata_service/api/swagger_doc/template.yml, metadata_service/entity/dashboard_detail.py, metadata_service/entity/tag_detail.py, metadata_service/proxy/atlas_proxy.py, metadata_service/proxy/base_proxy.py, metadata_service/proxy/gremlin_proxy.py, metadata_service/proxy/neo4j_proxy.py, metadata_service/proxy/statsd_utilities.py, setup.py, tests/unit/proxy/test_neo4j_proxy.py
Dashboard Detail API
Unit test has been added. Integration test has been done.
docstring
=> Dashboard Detail API

docs/configurations.md, docs/structure.md, metadata_service/api/user.py, metadata_service/config.py, tests/unit/api/test_user.py
Based on the discussion [here](https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1583268499086300), the requirement is to get the user details from LDAP (or any other custom system). This PR makes it possible to implement that custom function via configurations.
NA
Added the relative documentation on how to configure that. 
=> Implements the support for custom user detail function via config.py

requirements.txt
=> Upgrade MarkupSafe to 1.1

metadata_service/__init__.py, metadata_service/api/dashboard.py, metadata_service/api/swagger_doc/tag/tag_delete.yml, metadata_service/api/swagger_doc/tag/tag_put.yml, metadata_service/api/table.py, metadata_service/api/tag.py, metadata_service/proxy/atlas_proxy.py, metadata_service/proxy/base_proxy.py, metadata_service/proxy/gremlin_proxy.py, metadata_service/proxy/neo4j_proxy.py, setup.py, tests/unit/api/dashboard/dashboard_test_case.py, tests/unit/api/dashboard/test_dashboard_tag_api.py, tests/unit/api/tag/test_tag_common.py, tests/unit/proxy/test_atlas_proxy.py, tests/unit/proxy/test_neo4j_proxy.py
Added:
- Dashboard Tag API
Updated:
- Consolidated Tag logic into one.
Unit test has been added. Integration test has been done.
docstring
=> Dashboard tag API

metadata_service/proxy/neo4j_proxy.py, requirements.txt, setup.py
=> Update common deps

metadata_service/__init__.py, requirements.txt
Small twist to support CORS calls
=> Add Cors support in the app

metadata_service/__init__.py, metadata_service/api/swagger_doc/user/follow_delete.yml, metadata_service/api/swagger_doc/user/follow_put.yml, metadata_service/api/user.py, metadata_service/entity/resource_type.py, metadata_service/proxy/atlas_proxy.py, metadata_service/proxy/base_proxy.py, metadata_service/proxy/gremlin_proxy.py, metadata_service/proxy/neo4j_proxy.py, setup.py, tests/unit/api/test_user.py, tests/unit/proxy/test_atlas_proxy.py, tests/unit/proxy/test_neo4j_proxy.py
Currently, follow API & proxy internally assumes that it's for Table. This PR is to make it work with any resource.
Unit test has been updated. Integration test has been done.
docstring
=> Making bookmark (follow) to utilize resource type

metadata_service/api/swagger_doc/template.yml, metadata_service/api/user.py, metadata_service/entity/dashboard_detail.py, metadata_service/proxy/atlas_proxy.py, metadata_service/proxy/base_proxy.py, metadata_service/proxy/gremlin_proxy.py, metadata_service/proxy/neo4j_proxy.py, requirements.txt, setup.py, tests/unit/api/test_user.py, tests/unit/proxy/test_neo4j_proxy.py
Added:
- Dashboard in List bookmark API
- Last successful run timestamp and URL on GET Dashboard detail API
Updated unit tests and performed integration test.
docstring
=> Add Dashboard on List bookmark API

requirements.txt
Updates the version of amundsen common package. 
=> Bump the version of amundsen common

metadata_service/proxy/neo4j_proxy.py, setup.py, tests/unit/proxy/test_neo4j_proxy.py
Added query_name, chart_name and tables in Dashboard detail GET API.
(Note that `chart_name` won't be available from Mode because of the issue with Mode API)
Updated unit tests. Performed integration tests
N/A
=> Added query names, chart names, tables in Dashboard detail GET API

metadata_service/api/swagger_doc/user/own_get.yml, metadata_service/api/user.py, setup.py, tests/unit/api/test_user.py
Added Dashboard to User owned resources GET API
Integration test. Updated unit test
N/A
=> Added Dashboard to User owned resources GET API

metadata_service/proxy/neo4j_proxy.py, setup.py
Bug fix on Dashboard detail Cypher query
Integration test
n/a
=> Bug fix on Dashboard detail Cypher query

docs/proxy/atlas/popular_tables.md, docs/proxy/atlas_proxy.md, metadata_service/proxy/atlas_proxy.py, tests/unit/proxy/fixtures/atlas_test_data.py, tests/unit/proxy/test_atlas_proxy.py
adapt atlas_proxy to [amundsenatlastypes](https://github.com/dwarszawski/amundsen-atlas-types) == 1.0.2 
modified test_atlas_proxy accordingly
=> adapt atlas_proxy to new model of amundsenatlastypes==1.0.2

metadata_service/proxy/neo4j_proxy.py, setup.py
=> Return distinct query, chart for a given dashboard

docs/configurations.md, metadata_service/config.py, metadata_service/proxy/atlas_proxy.py, tests/unit/proxy/fixtures/atlas_test_data.py, tests/unit/proxy/test_atlas_proxy.py
This change provides formatting for column statistics collected by AtlasProxy. Without proper formatting, the UI can be unreadable and cluttered when raw statistics are not formatted:
After the change the stats will be presented in much pleasant way.
Adjusted tests and run to succesfull completion.
n/a
=> Format column statistics in AtlasProxy

metadata_service/proxy/atlas_proxy.py, tests/unit/proxy/fixtures/atlas_test_data.py, tests/unit/proxy/test_atlas_proxy.py
When listing columns in tables view there is no check if the column is still active. This might lead to showing inaccurate results.
Aligned, extended & run to completion.
=> Hide inactive columns in table view (AtlasProxy)

metadata_service/proxy/neo4j_proxy.py, requirements.txt, tests/unit/proxy/test_neo4j_proxy.py
=> Fix user unit test

metadata_service/api/swagger_doc/template.yml, metadata_service/entity/dashboard_detail.py, metadata_service/entity/dashboard_query.py, metadata_service/proxy/neo4j_proxy.py, setup.py, tests/unit/proxy/test_neo4j_proxy.py
Add query text and query URL into Dashboard detail API
Updated unit test.
Performed integration test in local.
N/A
=> feat: Add query text and query URL into Dashboard detail API

metadata_service/proxy/atlas_proxy.py, metadata_service/proxy/gremlin_proxy.py
Passing the function causes 404, and thus crashing the frontend. This will make sure not to crash the frontend and simply returns 0 resources. 
Second fix is when there is no position attribute available for table, we can't apply sort function on those tables. hence making it 9999 to simply put that table at the end. 
NA
NA
=> fix: Returns the empty dictionary to gracefully fail

.travis.yml
Update repo name in travis file
=> ci: Update repo name in travis file

metadata_service/proxy/atlas_proxy.py, tests/unit/proxy/fixtures/atlas_test_data.py, tests/unit/proxy/test_atlas_proxy.py
Add support for get_latest_updated_ts in AtlasProxy
=> feat: Get last updated ts for AtlasProxy

.github/workflows/pypipublish.yml, Makefile
fix https://github.com/amundsen-io/amundsen/issues/658
=> chore: fix docker push script

metadata_service/proxy/atlas_proxy.py, tests/unit/proxy/fixtures/atlas_test_data.py, tests/unit/proxy/test_atlas_proxy.py
Fixes the Owned By feature on the user profile page. Also fixes a bug where the config method to get the user detail was getting extra unexpected arguments in some cases. Makes the code more readable and easy to maintain. 
NA
NA
=> fix: Improvements to the Owned By feature

.github/workflows/pypipublish.yml, Makefile
=> chore: update make target name

.github/workflows/pull_request.yml
=> chore: add codecov action

requirements.txt, tests/unit/api/dashboard/dashboard_test_case.py, tests/unit/api/table/table_test_case.py, tests/unit/api/table/test_table_badge_api.py, tests/unit/api/tag/test_tag_common.py, tests/unit/api/test_column_description_api.py, tests/unit/api/test_popular_tables_api.py, tests/unit/api/test_redshit_disable_comment_edit.py, tests/unit/api/test_user.py, tests/unit/proxy/test_atlas_proxy.py, tests/unit/proxy/test_neo4j_proxy.py, tests/unit/proxy/test_statsd_utilities.py
=> chore: remove unused libs

metadata_service/proxy/atlas_proxy.py
Signed-off-by: verdan <verdan.mahmood@gmail.com>
To make the union of the fallback owner and the selected owner, we need to have the union of both to make sure we display the complete owners information, and to also display the owned by resources on the user details page. 
Not Applicable.
Not Applicable
=> chore: Improvements to Data Owner feature in Atlas

metadata_service/proxy/atlas_proxy.py, tests/unit/proxy/fixtures/atlas_test_data.py
Signed-off-by: verdan <verdan.mahmood@gmail.com>
This PR fixes a scenario where the user's owned resources does not return anything. 
This PR fixes a scenario where the user's owned resources does not return anything, based on the new version of the atlas entity definitions. 
NA
NA
=> chore: Fixes the edge case of Data Owner for Atlas proxy

docs/proxy/atlas_proxy.md, metadata_service/proxy/atlas_proxy.py, tests/unit/proxy/fixtures/atlas_test_data.py, tests/unit/proxy/test_atlas_proxy.py
Signed-off-by: verdan <verdan.mahmood@gmail.com>
=> test: Updates the test cases, and documentation for Atlas Proxy

requirements.txt
New amundsen common version will break badges due to change in Table schema.
N/A
N/A
=> fix: (temporary) made version equal to 3.6 to prevent badge issues

docs/configurations.md, metadata_service/api/badge.py, metadata_service/api/dashboard.py, metadata_service/api/swagger_doc/badge/badge_delete.yml, metadata_service/api/swagger_doc/badge/badge_get.yml, metadata_service/api/swagger_doc/badge/badge_put.yml, metadata_service/api/swagger_doc/template.yml, metadata_service/api/table.py, metadata_service/entity/badge.py, metadata_service/proxy/atlas_proxy.py, metadata_service/proxy/base_proxy.py, metadata_service/proxy/gremlin_proxy.py, metadata_service/proxy/neo4j_proxy.py, tests/unit/api/badge/test_badge_common.py, tests/unit/api/dashboard/test_dashboard_badge_api.py, tests/unit/api/table/test_table_badge_api.py, tests/unit/api/table/test_table_detail_api.py, tests/unit/api/tag/test_tag_common.py, tests/unit/proxy/test_neo4j_proxy.py
Removed all badge_type fields in Badge model
Removed badge_type from tests that use badges
N/A
=> fix: removed all badge_type fields from API

metadata_service/proxy/neo4j_proxy.py, tests/unit/proxy/test_neo4j_proxy.py
Implement functionality to add badges to columns in metadata.
=> feat: return column level badges

public.Dockerfile, setup.py
Small PR bumping the version of the flaskoidc dependency. Environment variables in the dockerfile updated accordingly.
=> Fix: bumped flaskoidc dependency to v0.1.1

requirements.txt
same issue as  https://github.com/amundsen-io/amundsenfrontendlibrary/pull/697/files
=> chore: fix deps

metadata_service/config.py
=> feat: AddSwaggerEnabledAsEnvVar

setup.py
Major release given that we no longer support old badges.
N/A
N/A
=> chore: updated version of library for new release

metadata_service/config.py
=> chore: add neptune proxy to config

metadata_service/proxy/neo4j_proxy.py
Current 'get_tags' query only return Table related tag.
Edit 'get_tags' neo4j query to return all Resource tag list.
=> Fix: Edit get_tags query

metadata_service/__init__.py, metadata_service/api/popular_tables.py, metadata_service/proxy/atlas_proxy.py, metadata_service/proxy/base_proxy.py, metadata_service/proxy/gremlin_proxy.py, metadata_service/proxy/neo4j_proxy.py, tests/unit/api/test_popular_tables_api.py
Signed-off-by: Josh Howard <joshthoward@gmail.com>
The popular_tables endpoint has been updated to allow for an optional user_id. The idea is that the popular tables response should be able to be user specific. 
Minor updates to fix `assert_called_with` calls. 
- [-] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
- [-] PR includes a summary of changes.
- [-] PR adds unit tests, updates existing unit tests, **OR** documents why no test additions or modifications are needed.
- [-] In case of new …
=> feat: Updated popular_tables endpoint to allow optional user_id

setup.py
=> chore: build a new release

.github/workflows/monthly_release.yml, .github/workflows/publish_release.yml, setup.cfg
Use python-semantic-release to bump version, create new release PRs and publish releases.
=> chore: added release to automate releases

metadata_service/proxy/atlas_proxy.py, metadata_service/proxy/base_proxy.py, metadata_service/proxy/gremlin_proxy.py, metadata_service/proxy/neo4j_proxy.py, requirements.txt
Added method to get lineage to base proxy and other proxies, can be implemented internally, and bumped common version.
=> feat: added get_lineage method to neo4j proxy

metadata_service/proxy/atlas_proxy.py, tests/unit/proxy/fixtures/atlas_test_data.py, tests/unit/proxy/test_atlas_proxy.py
This PR introduces support for surfacing column badges in Atlas Proxy.
TBD
n/a
=> feat: Column badges in Atlas Proxy

public.Dockerfile
build image with git to install link dependency (marshmallow-annotations), will probably have to do this for every repo where we update amundsen-common which uses new version of marshmallow
=> fix: added git install to docker file so we can install link dependencies

.github/workflows/publish_release.yml
added docker publish, need to do for other repos
=> fix: added job to publish to docker for monthly release publish step

metadata_service/config.py, metadata_service/proxy/neptune_proxy.py, requirements.txt, tests/unit/proxy/roundtrip/test_neptune_proxy.py
Related to https://github.com/amundsen-io/amundsenmetadatalibrary/pull/270
Fixed tests so that they use the new configuration. 
=> refactor: Remove Global call

.github/CODEOWNERS
Removal per https://github.com/amundsen-io/amundsencommon/pull/98#discussion_r590908528 . also alphabetize
cc @allisonsuarez @feng-tao @verdan
=> chore: add myself to CODEOWNERS, remove Diksha

requirements.txt, setup.py
Signed-off-by: verdan <verdan.mahmood@gmail.com>
This PR makes sure that we install all the requirements when installing amundsenmetada via `pip install`.
=> fix: makes sure to install all requirements

.gitignore, metadata_service/entity/badge.py, metadata_service/entity/dashboard_detail.py, metadata_service/entity/dashboard_query.py, metadata_service/entity/dashboard_summary.py, metadata_service/entity/description.py, metadata_service/entity/tag_detail.py, requirements.txt, setup.py
Signed-off-by: Dmitriy Kunitskiy <dkunitskiy@lyft.com>
Context on marshmallow3-annotations in https://github.com/amundsen-io/amundsencommon/pull/101 and linked issue
wsgi starts error-free
=> chore: amundsencommon and switch to marshmallow3-annotations

metadata_service/proxy/atlas_proxy.py, tests/unit/proxy/test_atlas_proxy.py
Signed-off-by: sinkuladis <sink.vlad@gmail.com>
With this PR table reports are sorted alphabetically.
Added test for _get_reports method.
No documentation added or modified.
=> fix: Sort reports alphabetically

.dependabot/config.yml
Signed-off-by: Dorian Johnson <2020@dorianj.net>
The Amundsen project [moved to a monorepo](https://github.com/amundsen-io/rfcs/pull/31). This repository will be kept up temporarily to allow users to transition gracefully, but new PRs won't be accepted.
=> chore: remove dependabot
