amundsen-io/amundsenmetadatalibrary

metadata_service/__init__.py, metadata_service/api/user.py, metadata_service/entity/user_detail.py, metadata_service/proxy/neo4j_proxy.py, setup.py, tests/unit/test_neo4j_proxy.py
The user model for "Amundsen People" could be found in https://github.com/lyft/amundsendatabuilder/blob/master/databuilder/models/user.py.
Add an API endpoint to fetch user based on user_id(email).
Test the endpoint locally with staging neo4j data:
```
curl http://localhost:5000/user/'tfeng@lyft.com'
{"email": "tfeng@lyft.com", "first_name": "Tao", "last_name": "Feng", "full_name": "Tao Feng", "is_active": true, "github_username": "", "slack_id": "", "team_name": "Data Platform", "employee_type": "teamMember"}
```
The databuilder has some issues on `github_user_name` field, but that would be a separate pr to fix.
Endpoint for bookmark, own, used three relationships will be in a separate pr.
=> Add an API endpoint to fetch user information

metadata_service/__init__.py, metadata_service/api/user.py, metadata_service/proxy/neo4j_proxy.py, metadata_service/util.py, setup.cfg, setup.py, tests/unit/test_neo4j_proxy.py
Test locally with staging data which works:
action in { own, follow, read}
```
curl http://localhost:5000/user/tfeng@lyft.com/action/
curl -v -x PUT http://localhost:5000/user/tfeng@lyft.com/action/hive%3A%2F%2Fgold.default%2Ftable_name
curl -v -x DELETE http://localhost:5000/user/tfeng@lyft.com/action/hive%3A%2F%2Fgold.default%2Ftable_name
```
todo:
1. will create a separate pr to refactor existing table_owner endpoint to use the new generic endpoint.
2. currently it doesn't take type as url input parameter which requires larger refactor. I plan to do(create a ticket) once we have the dashboard feature coming in.
Design qq:
1. do we need to support put/delete for read or user API?
2. do we need to allow FE to pass a threshold to the read API endpoint? Currently based on staging data, I …
=> [Amundsen People] Add API to build relationship between user and table

metadata_service/proxy/atlas_proxy.py, setup.py, tests/unit/proxy/test_atlas_proxy.py
This PR extends the functionality of Apache Atlas, and using existing attributes of Atlas, it implements the owner, description, and tags functionality on the detail pages. 
Added Todos and FixMe's where needed for now. 
FYI: @feng-tao @jinhyukchang
=> Table Detail APIs improvements

setup.py
We are not going to have more dependencies to make Apache Atlas work with the Amundsen, so it is safe to keep it in the same dependencies list
=> Make atlasclient a default dependency

.gitignore
As discussed in https://github.com/lyft/amundsenmetadatalibrary/pull/27#issuecomment-486065064
I plan to follow up with changes as needed to bring the 3 other `lyft/amundsen*` repos on par.
=> gitignore /dist folder avoids :egg:s in commits!

metadata_service/api/table.py, metadata_service/entity/table_detail.py, metadata_service/proxy/neo4j_proxy.py, setup.py, tests/unit/proxy/test_neo4j_proxy.py
This PR is to add `is_view` field to TableDetailAPI payload, so frontend can get the value and differentiate Views from Tables.
=> add is_view field to TableDetailAPI payload

README.md, metadata_service/__init__.py, metadata_service/config.py, requirements.txt
Updates the default config to take PROXY_CLIENT from the environment. This allows the docker image to use Apache Atlas without changes.
=> Describe and make easier Apache Atlas integration

metadata_service/config.py, metadata_service/proxy/atlas_proxy.py, setup.py, tests/unit/proxy/test_atlas_proxy.py
This PR fixes following issue: https://github.com/lyft/amundsenmetadatalibrary/issues/32
Also bumps the version of metadata, since we recently made the queries efficient and made the atlas attributes more configurable based on user's deployments of Apache Atlas.
=> Support for upcoming version of Apache Atlas

README.md
Make sure you have checked **all** steps below.
- Example: "Updates the version of Flask to v1.0.2"
Closes #20 - the old readme.md didn’t include full docker name including user/ 
Just documentation fix
1. Subject is separated from body by a blank line
1. Subject is limited to 50 characters (not including Jira issue reference)
1. Subject does not end with a period
1. Subject uses the imperative mood ("add", not "adding")
1. Body wraps at 72 characters
1. Body explains "what" and "why", not "how"
Just documentation fix
=> Doc fix: Docker pull new official image

metadata_service/proxy/neo4j_proxy.py, tests/unit/proxy/test_neo4j_proxy.py
Make sure you have checked **all** steps below.
- Example: "Updates the version of Flask to v1.0.2"
Address this issue mentioned by OSS slack(https://amundsenworkspace.slack.com/archives/CHQERT0D7/p1556823283047700)
1. Subject is separated from body by a blank line
1. Subject is limited to 50 characters (not including Jira issue reference)
1. Subject does not end with a period
1. Subject uses the imperative mood ("add", not "adding")
1. Body wraps at 72 characters
1. Body explains "what" and "why", not "how"
=> Fix bug of latest_timestamp when data not available

metadata_service/proxy/neo4j_proxy.py, tests/unit/proxy/test_neo4j_proxy.py
Make sure you have checked **all** steps below.
- I hope so 😄 
- when `amundsen_updated_timestamp` does not exist in neo4j, the `record` returned can be None. Under these circumstances, `record` cannot respond to a `get` call, resulting in an uncaught exception. This patch returns None instead, and changes the return type hint to Optional[int]
- <img width="1259" alt="Before stacktrace screenshot" src="https://user-images.githubusercontent.com/1591459/57107915-8754ab00-6cee-11e9-86e0-a7acc30b2f3b.png">
- <img width="1293" alt="After stacktrace screenshot" src="https://user-images.githubusercontent.com/1591459/57107945-99cee480-6cee-11e9-82a5-31f3b4c3c7b7.png">
- `tests/unit/proxy/test_neo4j_proxy.py` has been updated
1. Subject is separated from body by a blank line
1. Subject is limited …
=> get_latest_updated_ts now returns None when record from neo4j is None

setup.py
Also tweaked description to be similar to search service
Currently if you go to pypi and click the homepage link you’ll get a 404
=> Fix setup.py GitHub url

metadata_service/api/user.py, metadata_service/proxy/neo4j_proxy.py, setup.py, tests/unit/proxy/test_neo4j_proxy.py
When building Amundsen people, we found that it is not necessary to use Table model when return table object to FE. The table model contains all the metadata related table detail page which the payload size is huge. Switch to use popularTable model.
=> Use PopularTable model when return user resource

metadata_service/proxy/neo4j_proxy.py, setup.py, tests/unit/proxy/test_neo4j_proxy.py
1. Relationship of `manage_by` should be in upper case
2. BoltStatementResult is not None even user_id is invalid. We should check whether `single_result`
is None instead
3. Bump up amundsenmetadatalibrary version
_What tests did you add or modify and why? 
1. Added test to ensure NotFoundException is raised in get_user_detail function if input user email is invalid.
- All the public functions and the classes in the PR contain docstrings that explain what it …
=> Fix neo4j_proxy get_user_detail api method and bump up version

metadata_service/proxy/neo4j_proxy.py, setup.py
Remove `on MATCH` statement in add_owner method, because it will update existing record with only `email` and `key` field and remove all other attributes.
=> remove on match statement in add owner method

metadata_service/api/user.py, metadata_service/proxy/atlas_proxy.py, metadata_service/proxy/base_proxy.py, metadata_service/proxy/neo4j_proxy.py, setup.py, tests/unit/proxy/test_neo4j_proxy.py
Previously, Metadata service was performing queries against each columns unnecessarily while getting bookmarked table. This change is to remove those query against columns.
Additionally, refactored query that retrieves frequently used table to fetch the one with `published_tag` and to get latest read data up to 50 tables.
Unit tested. Integration tested locally.
N/A
=> Improve performance of getting bookmarked tables, refactored getting freq read table query

metadata_service/proxy/neo4j_proxy.py, setup.py
Removed double bracelet that was used to escape when str is used with `format` method. `format` method has been removed and Cypher is failing.
Tested
N/A
=> Hot fix on frequently read table query

README.md, public.Dockerfile, setup.py
Have all execution command into CMD so that execution of Docker is flexible enough to support other WSGI web-server such as gunicorn.
Example:
`docker run -p 5000:5000 amundsendev/amundsen-metadata gunicorn --bind 0.0.0.0:5000 metadata_service.metadata_wsgi`
Tested in local
Updated README.md
=> Updated Dockerfile to be flexible

metadata_service/proxy/atlas_proxy.py, tests/unit/proxy/test_atlas_proxy.py
* This PR includes caching of popular tables API for atlas proxy.
* Implementation is similar to neo4j's and uses beaker.
* Added _get_metadata_collection function which isolates the two atlas calls for fetching metadata id and metadata collection.
* Changed test cases in `test_atlas_proxy.py`
Nothing was added or removed.
- [ *] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
- [*] PR includes a summary of changes. 
- [*] PR adds unit tests, updates existing unit tests, __OR__ documents why no …
=> Added cache for atlas proxy popular table API.

metadata_service/__init__.py, metadata_service/api/column.py, metadata_service/api/table.py, setup.py, tests/unit/api/test_redshit_disable_comment_edit.py
Introduced support of Markdown descriptions for tables & columns.
This module changes are intended to pass description text as a request body (instead of using URI parameter).
[Related changes at amundsenfrontendlibrary.](https://github.com/lyft/amundsenfrontendlibrary/pull/298)
Unit tests for table and column description upsertion have been modified
Markdown description format demo:
https://rexxars.github.io/react-markdown/
=> Improve table & columns description formatting (#98)

README.md
Will scroll past GitHub repo folders (specially more handy on small screens like phones/tablets)
Like lyft/amundsendatabuilder#147
Also reduce duplication for Docker w/wo Gunicorn
=> Link deeper to doc content, simpler Docker README

Makefile, setup.cfg, tests/unit/api/test_column_description_api.py, tests/unit/api/test_popular_tables_api.py, tests/unit/proxy/fixtures/atlas_test_data.py, tests/unit/proxy/test_atlas_proxy.py
I am trying to make it easier for us (and everyone, I guess) to refresh from upstream code. I added mypy coverage to test files and cleaned up outstanding mypy issues in those files. I also upped the minimum test coverage to 75% from 0. Not sure when that number was cleared...
=> Increase test percentage minimum and add mypy checks to test files

docs/proxy/gremlin.md, docs/proxy/neptune.md, metadata_service/config.py, metadata_service/proxy/aws4authwebsocket/transport.py, metadata_service/proxy/gremlin_proxy.py, metadata_service/proxy/janus_graph_proxy.py, metadata_service/proxy/neptune_proxy.py, requirements.txt, setup.cfg, tests/unit/proxy/abstract_gremlin_proxy_tests.py, tests/unit/proxy/abstract_proxy_tests.py, tests/unit/proxy/aws4authwebsocket/test_transport.py, tests/unit/proxy/test_janus_graph_proxy.py, tests/unit/proxy/test_neptune_proxy.py
I know there are people interested in using a gremlin proxy for amundsen. We are still in the process of tweaking a few things, but I thought I would make an effort to get a base PR up while everyone is out over the holidays. Locally we actually have done all the work of writing the shared methods in gremlin, but I will follow up with that code later. Hopefully this is at least helpful to teams that are waiting / wanting to use gremlin.
I added test setup, but did not add tests specifically related to janusgraph or neptune right now. I did add tests for the aws transport file that I added for the neptune proxy.
I added documentation for janusgraph and neptune.
- In case you are adding a dependency, check if the …
=> Add basic setup for using a gremlin proxy

README.md, metadata_service/metadata_wsgi.py
Change the default port to 5002. Currently all wsgi try to start up with the default port, so it's easier/free to start up all 3 servers for local debugging if they each have a different port.
This is kind of speculative --  WDYT? If ya'll are like us, you've customized the port for your individual circumstances anyway, but if you're expecting the port to be 5000, this will cause some problems...
Config/port change. No tests affected.
Changed port number to 5002.
- All the public functions and the classes in the PR contain docstrings that explain what it …
=> change default port to 5002

metadata_service/api/table.py, setup.py, tests/unit/api/table/test_table_badge_api.py
This PR is to not allow same Tag value and Badge value for Badge is special Tag.
Also, if it's allowed it would change the type existing badge or tag as value is the unique constraint of Neo4j.
Integration test performed.
N/A
=> Do not allow tag and badge to have same value

metadata_service/proxy/atlas_proxy.py, metadata_service/proxy/base_proxy.py, metadata_service/proxy/gremlin_proxy.py, metadata_service/proxy/neo4j_proxy.py, setup.py, tests/unit/api/test_user.py, tests/unit/proxy/test_neo4j_proxy.py
A follow up to my previous PR, which adds a BaseAPI with some generic logic. That logic expects "id" as an argument for the "get" method. This PR replaces user_id with id. 
I updated the user API test to use `assert_called_once_with` so that this bug can be caught in the future via automated testing.
=> Switch from user_id to id in get_user method

metadata_service/api/user.py, requirements.txt, setup.py
Recent [PR](https://github.com/lyft/amundsenmetadatalibrary/pull/99) brought backward incompatible change to "user follows" API and this PR is to revert the change.
Also, uses amundsen-common==0.1.3rc0 for 0.1.3 is for Python>=3.7 and it is not compatible with other micro-services.
This is a short term fix to fix broken master branch. 
Integration test done.
N/A
=> Reverting user follows API from using PopularTableSchema

metadata_service/api/table.py, metadata_service/proxy/base_proxy.py, metadata_service/proxy/neo4j_proxy.py, requirements.txt, setup.py, tests/unit/api/table/test_table_detail_api.py, tests/unit/proxy/test_neo4j_proxy.py
https://github.com/lyft/amundsen/issues/147
I added the inclusion of programmatic descriptions in the returned table metadata object.
I modified the proxy-neo4j tests to test for programmatic description.
None added.
=> Added programmatic description fields

metadata_service/api/swagger_doc/template.yml, metadata_service/api/swagger_doc/user/follow_get.yml, metadata_service/entity/dashboard_detail.py, metadata_service/proxy/neo4j_proxy.py, setup.py, tests/unit/proxy/test_neo4j_proxy.py
Updated:
- Added `product` and `recent_view_count` to Dashboard Detail GET API and Bookmarks GET API
- Neo4j Cypher query to perform early aggregation for better performance.
Updated unit tests. Performed integration tests.
N/A
=> Add product and recent_view_count to Dashboard APIs

metadata_service/proxy/atlas_proxy.py, tests/unit/proxy/fixtures/atlas_test_data.py, tests/unit/proxy/test_atlas_proxy.py
With this PR:
- Bookmarks feature has been brought back to life
- Issue with retrieving other users bookmarks was fixed - when user A bookmarked user's B table, user B could also see it in his `My Bookmarks` section (assuming that db name is users id)
- Retrieval of deleted Bookmarks has been turned off
- New methods are added (create_user, user_exists) that can be used to add users to atlas automatically
Please note that it requires amundsenatlastypes in **1.1.0** version, where `Bookmark` entity was introduced.
Aligned tests to new entity definitions.
- In case you are adding a dependency, check if the license complies …
=> Fix Bookmarks after latest changes (AtlasProxy)

metadata_service/proxy/atlas_proxy.py, tests/unit/proxy/fixtures/atlas_test_data.py, tests/unit/proxy/test_atlas_proxy.py
Atlas is returning timestamp in milliseconds, however Amundsen relies on Unix Epoch. This causes a bug in rendering the date in Table View UI.
Aligned & run to successful completion.
=> Fix timestamp format of latest edit field [AtlasProxy]

metadata_service/api/swagger_doc/template.yml, metadata_service/config.py, metadata_service/proxy/neo4j_proxy.py, setup.py, tests/unit/proxy/test_neo4j_proxy.py
Add `mode_user_id` into User detail API.
- Supports `other_key_values` in User detail API so that any other attributes in User node can configured to put into the API response.
Example:
```
User registered with Mode
{
"email": "john@foo.com",
"employee_type": "teamMember",
"is_active": true,
...
"other_key_values": {
"mode_user_id": "foo_bar"
},
...
}
User not registered with Mode
{
"email": "john2@foo.com",
"employee_type": "teamMember",
"is_active": true,
...
"other_key_values": {},
...
}
```
Updated unit test. Performed integration test.
N/A
- All the …
=> feat: Add mode_user_id into User detail API

metadata_service/proxy/neo4j_proxy.py, setup.py
Recent Neo4j driver [upgrade](https://github.com/lyft/amundsenmetadatalibrary/pull/139) broke many add/delete APIs and this is due to behavior change of Neo4j driver.
- Remove tx.close() due to the behavior change from 1.7.2 that tx.commit() closes the transaction and following tx.close() call throws exception.
`  File \"python3.6/site-packages/neo4j/__init__.py\", line 853, in _assert_open
raise TransactionError(\"Transaction closed\")
neo4j.TransactionError", "call_site": "site-packages/metadata_service/api/user.py:142", "uri_path": "/user/jinchang@lyft.com/follow/table/hive://gold.*****/********", "revision": "4735a73662", "msg": "UserFollowAPI DELETE Failed"}
`
Integration test done on APIs below:
- add description
- add owner
- delete owner
- add tag
- delete tag
- add bookmark
- …
=> fix: Remove tx.close() with Neo4j driver upgrade

metadata_service/proxy/atlas_proxy.py, requirements.txt, tests/unit/proxy/fixtures/atlas_test_data.py, tests/unit/proxy/test_atlas_proxy.py
This change enables Frequent Users feature in Table Detail View and My Profile section.
=> feat: Add Frequent Users feature in [AtlasProxy]

metadata_service/config.py, metadata_service/proxy/atlas_proxy.py, tests/unit/proxy/fixtures/atlas_test_data.py, tests/unit/proxy/test_atlas_proxy.py
This MR introduces parsing of programmatic descriptions using **parameters** field of Table entity in Atlas Proxy. The parameters field is a map of String -> Any and seems like a perfect fit for this usecase.
Moreover, this property can be set for example on hive_table entity programatically with spark sql:
`ALTER [TABLE|VIEW] table_name SET TBLPROPERTIES (key1=val1, key2=val2, ...)` - Atlas hive-hook will propagate such action in Hive Metastore to Atlas metadata
All of those key1, key2 etc then become programmatic description entries.
The idea is also to have a filter to remove unwanted properties (like spark technical ones that appear in parameters after creating table with spark). This could also be of use for other proxies.
Tested for presence and filtering of programmatic …
=> feat: Add programmatic descriptions parser for [AtlasProxy]

metadata_service/config.py, metadata_service/proxy/atlas_proxy.py, requirements.txt, tests/unit/proxy/fixtures/atlas_test_data.py, tests/unit/proxy/test_atlas_proxy.py
Add resource_reports field in Table API ( atlas proxy)  to support integration with tools generating static HTML reports, such as [popmon](https://github.com/ing-bank/popmon), [pandas-profiling]( https://github.com/pandas-profiling/pandas-profiling) or [great_expectations](https://github.com/great-expectations/great_expectations)..
Updated existing unit tests
N/A
Resolve lyft/amundsen#525
=> feat: Add resource_reports field in Table API ( Atlas proxy)

metadata_service/proxy/atlas_proxy.py
Add a period to distincly separate table name end. Otherwise, table which names overlaps with beginning of another tables name (like table_name and table_name_test) will present also readers for table_name_test.
=> fix: Overlapping table name issue in Readers [AtlasProxy]

metadata_service/proxy/atlas_proxy.py, tests/unit/proxy/fixtures/atlas_test_data.py, tests/unit/proxy/test_atlas_proxy.py
Distinguish between tables and table views based on tableType property of table in Atlas.
Extended mock and expected data.
-
=> feat: Populate is_view property in AtlasProxy

.github/workflows/pull_request.yml, .github/workflows/pypipublish.yml
Add two github actions (test, pypi), still missing the docker push which I add in a different pr. So I will keep the travis for now.
=> chore: add pypi publish action

docs/configurations.md, metadata_service/api/user.py, metadata_service/proxy/atlas_proxy.py, requirements.txt, tests/unit/proxy/test_atlas_proxy.py
=> feat: Data Owner Implementation of Atlas Proxy

metadata_service/proxy/atlas_proxy.py
There are some edge cases where `tableType` is not provided and hence > `is_view` recognition will fail.
=> bug: View recognition in Atlas Proxy

Makefile, requirements.txt, tests/unit/api/table/__init__.py, tests/unit/api/table/table_test_case.py, tests/unit/api/table/test_table_badge_api.py, tests/unit/api/table/test_table_detail_api.py
=> chore: fix docker push

metadata_service/config.py, metadata_service/proxy/atlas_proxy.py, tests/unit/proxy/fixtures/atlas_test_data.py, tests/unit/proxy/test_atlas_proxy.py
When a Table entry contains `partitions` entries, we should verify if these partitions are time based. And if so - Watermark objects (low/high) should be created and added to Table object. 
The assumption is that `name` of partition contains only partition value and we can parse this value to match one of the expected date formats (configured with WATERMARK_DATE_FORMATS option). Another assumption is that date format is consistent throughout all partitions of table.
Added tests with `partition` entities …
=> feat: Add Watermark entries for partitioned tables in AtlasProxy

metadata_service/proxy/neo4j_proxy.py, tests/unit/proxy/test_neo4j_proxy.py
Signed-off-by: dikshathakur3119 <dikshathakur@lyft.com>
Added Bidirectional relation to add/delete in case of user and owner relationship
When we add or delete an `OWNER` relation from UI, it only deletes one way relation whereas when we do it from extractor, it add bidirectional relations, which is causing some inconsistency in neo4j graph, and creating duplicate `OWNER_OF` relations. To make this consistent, bidirectional owner relations will be created by UI API as well.
No new tests added
- In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License …
=> fix: Add /delete bidirectional relations in case of owner

metadata_service/proxy/atlas_proxy.py
The lastest version of Atlas has a predefined type [rdbms_column](https://github.com/apache/atlas/blob/master/addons/models/2000-RDBMS/2010-rdbms_model.json#L169), which is assigned as a sub type of Column by [amundsenatlastypes](https://github.com/dwarszawski/amundsen-atlas-types). It has a attribute called "data_type" that is equivalent to Column.col_type.
=> fix: data_type as Column.col_type.

metadata_service/proxy/atlas_proxy.py, tests/unit/proxy/fixtures/atlas_test_data.py, tests/unit/proxy/test_atlas_proxy.py
Do not collect full partition entities and use displayText instead to get watermarks. This will be more efficient and performant approach especially with tables with a lot of partitions.
=> fix: Too many partitions in one Atlas query (Watermarks in Atlas Proxy)

docs/proxy/atlas_proxy.md, metadata_service/proxy/atlas_proxy.py, tests/unit/proxy/test_atlas_proxy.py
This PR introduces change in strategy for fetching frequent users for a table. Instead of using basic search, which proved to be unreliable when dealing with special characters (like dots) in qualifiedName prefix search, we created a new kind of relationship in amundsen-atlas-types and are relying on it being connected to a table.
Adjusted existing tests.
Changed minimum version of amundsen-atlas-types
=> feat: Improved readers fetching in Atlas proxy

tests/unit/proxy/roundtrip/test_neptune_proxy.py, tests/unit/proxy/test_neo4j_proxy.py, tests/unit/test_swagger.py
Signed-off-by: Wonyeong Choi <ciwnyg0815@gmail.com>
Since the `assertEquals` function has been deprecated, replaced it with the `assertEqual` function for all test files.
Passed all existing unit tests
pytest doc about deprecated function: https://docs.python.org/3.3/library/unittest.html#deprecated-aliases
=> chore: Change deprecated pytest function

metadata_service/proxy/neo4j_proxy.py
Signed-off-by: bluefa <chulyonga@gmail.com>
Make neo4j query "get_tags" no longer return "tag count 0" tag. 
=> fix: get_tags no longer return tag_count 0 tag

metadata_service/proxy/neo4j_proxy.py
Change `expire` from positional argument to keyword argument.
Or cache will never be refreshed.
Write a simple getRandNum function locally:
```
@_CACHE.cache('test', 1)
def getRandNum(input):
return random.randint(0, 10)
```
If I treat `expire` as a positional argument, above function will always return the same value.
However, after I change it to keyword argument:
```
@_CACHE.cache('test', expire=1)
def getRandNum(input):
return random.randint(0, 10)
```
The value will change every second.
- In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License …
=> fix: expire is a keyword argument for beaker cache

metadata_service/proxy/neo4j_proxy.py, tests/unit/proxy/test_neo4j_proxy.py
Added Neo4j backend implementation for popular tables personalization. Follow on from this [PR](https://github.com/amundsen-io/amundsenmetadatalibrary/pull/232).
From my previous comments, I would like to do further experimentation on building a real recommender system here, but that doesn't seem to be possible now due to lack of data. 
Test caching on new DB query.
N/A
- [-] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
- [-] PR includes a summary of changes.
- [-] PR adds unit tests, updates …
=> feat: Neo4j backend for popular tables personalization 

metadata_service/proxy/neo4j_proxy.py
When https://github.com/amundsen-io/amundsenmetadatalibrary/pull/233 is rebased, it reverted previous fix (https://github.com/amundsen-io/amundsenmetadatalibrary/pull/239/files). This pr reapplies the fix. 
=> fix: reapply previous fix

metadata_service/config.py, metadata_service/proxy/__init__.py, metadata_service/proxy/atlas_proxy.py
This PR adds a possibility to pass custom kwargs to Atlas proxy client. It be used to fine-tune parameters like timeout or num of retries. Since every client might accept different kind of extra parameters it might be easier to just have custom dictionary complementing 
=> feat: Enable custom keyword arguments in Atlas Proxy Client

metadata_service/proxy/gremlin_proxy.py, metadata_service/proxy/janus_graph_proxy.py, metadata_service/proxy/neo4j_proxy.py, metadata_service/proxy/neptune_proxy.py, tests/unit/proxy/test_create_proxy.py
Fix after adding additional kwarg to client create method
Added tests for get_client method
n/a
=> fix: Proxy client creation fails after adding client_kwargs

metadata_service/config.py, metadata_service/proxy/gremlin_proxy.py, metadata_service/proxy/neo4j_proxy.py, metadata_service/proxy/neptune_proxy.py, tests/unit/proxy/roundtrip/test_neptune_proxy.py, tests/unit/proxy/test_neo4j_proxy.py
Signed-off-by: Andrew Ciambrone <andrjc4@vt.edu>
Made changes to the Neptune proxy so that you can configure the s3_bucket via the configuration settings. Before you had to made changes to the code to do that. 
Added a Configuration for Neptune. 
Made shards optional in Neptune. 
Minor changes to the queries to be more compatible with the data builder.  
Made changes to the testing framework to be more compatible. 
- All the public functions and the classes …
=> fix: Compatibility changes  to the gremlin integration

metadata_service/__init__.py, metadata_service/api/__init__.py, metadata_service/api/popular_tables.py, metadata_service/api/swagger_doc/lineage/lineage_get.yml, metadata_service/api/swagger_doc/template.yml, metadata_service/api/table.py, metadata_service/api/user.py, metadata_service/entity/resource_type.py, metadata_service/proxy/neo4j_proxy.py, requirements.txt, setup.py, tests/unit/api/table/test_table_lineage_api.py, tests/unit/proxy/test_neo4j_proxy.py
- Created Table Lineage API
- Added Column to ResourceType enum
- Bumped version of amundsen-common
- Bumped version of marshmallow and marshmallow-annotations to align with amundsen-common
- Updated tests and uses of marshmallow to new version
- Wrote tests for Table Lineage API
- Updated users test to work with marshmallow update
- Manually tested API calls
- All the public functions and the …
=> feat: Table Lineage API

metadata_service/api/swagger_doc/template.yml, metadata_service/proxy/neo4j_proxy.py
Trying to fix field cannot be null issue
=> fix: swagger docs don't align with common entity

metadata_service/config.py, metadata_service/proxy/gremlin_proxy.py, metadata_service/proxy/neptune_proxy.py, requirements.txt
Signed-off-by: Andrew Ciambrone <andrjc4@vt.edu>
- Upgrades the metadata proxy requirements so that it uses amundsengremlin 0.0.9 which changes the description key to the same as the databuilders. 
- Removed the reset shards from the neptune proxy because that has been moved to amundsengremlin in 0.0.8
- fixed the default source to be "description" instead of "user" 
- In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License …
=> fix: Reconcile gremlin description writes with the Databuilder

metadata_service/api/swagger_doc/user/detail_put.yml, metadata_service/api/user.py, metadata_service/proxy/atlas_proxy.py, metadata_service/proxy/base_proxy.py, metadata_service/proxy/gremlin_proxy.py, metadata_service/proxy/neo4j_proxy.py, tests/unit/api/test_user.py, tests/unit/proxy/test_neo4j_proxy.py
- Exposed a `PUT` method for the user details API resource
- Added corresponding swagger docs
- New function to create or update user was added to the base proxy
- Function was implemented for Neo4j, added as placeholder for other proxies
This implementation heavily relies on the validation and pre-processing being done as part of `UserSchema().load({...})` to validate the inputs of the data provided in the API. As new fields / validation rules are added to the User schema there should _hopefully_ not be any changes to this API. When invoking the API any number of fields can be provided as long as the minimum required fields are provided.
To invoke the API directly, locally:
```python
import requests as r
data = {'email': 'an_email@aol.com', 'first_name': 'first', 'last_name': 'last'}
url …
```
=> feat: Create users in metadata backend via API
